projects:
  Onboarding:
    schemaPath: graphql/schema.json
    includes:
      - ''
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: ''
        docsFilePath: .
        region: ap-southeast-1
        apiId: u4agpiyz7vd27lhuveaynighre
extensions:
  amplify:
    version: 3
