projects:
  uat-onboarding:
    schemaPath: graphql/schema.json
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: graphql
        region: ap-southeast-1
        apiId: 3cyv3st2r5gm5ely5cfdyzretu
extensions:
  amplify:
    version: 3
