projects:
  DecApp:
    schemaPath: graphql/schema.json
    includes:
      - ''
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: graphql
        region: ap-southeast-1
        apiId: u4agpiyz7vd27lhuveaynighre
extensions:
  amplify:
    version: 3
