declare type TypeBusinessNature =
  | "Actuarial / Stats"
  | "Advertising"
  | "Agriculture"
  | "Architecture"
  | "Audit / Accounting / Tax / Legal / Company Secretary"
  | "Aviation"
  | "Building / Construction Related"
  | "Business in Low Density Goods (E.g. Mobile Phones, Clothing)"
  | "Cash Intensive Business (E.g. Restaurant / Convenient Store)"
  | "Casino / Betting / Gambling Related"
  | "Chemical Engineering"
  | "Chemistry"
  | "Creative / Graphics"
  | "Education"
  | "Electronics Engineer"
  | "Engineering"
  | "Entertainment Outlets / Karaoke / Spa / Massage / Internet Cafe)"
  | "Financial / Capital Market Institution"
  | "Food Technology"
  | "Freight / Shipping"
  | "Geology"
  | "Government / Regulatory Authority"
  | "Healthcare"
  | "Hotel / Travel Services"
  | "Investment Holding"
  | "IT / Computer"
  | "Legal"
  | "Manufacturing"
  | "Marketing"
  | "Mechanical Engineering"
  | "Media / Entertainment"
  | "Medical / Health / Science"
  | "Money Services Business"
  | "Municipal Council"
  | "Non-governmental Organisation (Ngo)"
  | "Offshore Banking / Offshore Trust"
  | "Others"
  | "Pawnshop / Dealers in Precious Goods (E.g. Arts, Antique, Gold)"
  | "Personal Care"
  | "Property Development"
  | "Public Relations"
  | "QC / QA / Inspection"
  | "Quantity Surveyor"
  | "Real Estate / Property"
  | "Science / Technology"
  | "Secretarial"
  | "Social Service"
  | "Telecommunication"
  | "Trading"
  | "Training"
  | "Uniformed Bodies";

declare type TypeBusinessNatureValue = { value: TypeBusinessNature };
