declare type TypeOccupation =
  | "Account Assistance"
  | "Accountant"
  | "Advisory / Consultant"
  | "Agency Manager"
  | "Agent"
  | "Architect"
  | "Armed Forces"
  | "Artist"
  | "Banker"
  | "Beautician / Stylist"
  | "Business Owner"
  | "CEO"
  | "Chancellor / Dean  / Professor  / Lecturer / Fellow"
  | "Chef / Cook / F And B Serve Team"
  | "Civil Servant"
  | "Claim Processor"
  | "Clerical"
  | "Co-partner"
  | "Coach / Instructor / Trainer"
  | "Customer Service"
  | "Designers / Interior Designer / Decorator"
  | "Director"
  | "Doctor"
  | "Engineer"
  | "Executive"
  | "Farmer"
  | "Government"
  | "Homemaker"
  | "Housewife"
  | "Insurance Advisor"
  | "Lawyer"
  | "Management"
  | "Manager"
  | "Office & Executive"
  | "Others"
  | "Pensioner"
  | "Pharmacist / Pharmacologist"
  | "Politician"
  | "Professional"
  | "Programmer / Analyst / Admin-IT"
  | "Sales"
  | "Secretary"
  | "Self Employed"
  | "Skill Workers"
  | "Student"
  | "Supervisor"
  | "Surveyor"
  | "Teacher / Supervisor"
  | "Unemployed"
  | "Uniformed Bodies";

declare type TypeOccupationLabelValue = { label: string; value: TypeOccupation };
