import { Language } from "../../../constants";
import {
  DICTIONARY_ACCOUNT_TYPE,
  DICTIONARY_COUNTRIES,
  DICTIONARY_CURRENCY,
  DICTIONARY_ID_OTHER_TYPE,
  DICTIONARY_ID_TYPE,
  DICTIONARY_MOBILE_CODE,
} from "../../../data/dictionary";
import { ClientState, PersonalInfoState } from "../../../store";

const { PERSONAL_DETAILS } = Language.PAGE;

export const ClientData: ClientState = {
  accountType: DICTIONARY_ACCOUNT_TYPE[1],
  details: {
    accountHolder: undefined,
    principalHolder: {
      clientId: undefined,
      name: "Edgar Constantine",
      country: "",
      dateOfBirth: "",
      id: "880808-08-8888",
      idType: DICTIONARY_ID_TYPE[0],
      otherIdType: DICTIONARY_ID_OTHER_TYPE[0].value,
    },
    jointHolder: {
      clientId: undefined,
      name: "Jane Constantine",
      country: "",
      dateOfBirth: "",
      id: "EC4744643",
      idType: DICTIONARY_ID_TYPE[0],
      otherIdType: DICTIONARY_ID_OTHER_TYPE[0].value,
    },
    verified: false,
    initId: undefined,
  },
};

export const PersonalData: PersonalInfoState = {
  cancelOnboarding: false,
  editMode: false,
  editPersonal: false,
  editDeclaration: false,
  emailOtpSent: false,
  epfInvestment: false,
  epfShariah: false,
  incomeDistribution: PERSONAL_DETAILS.OPTION_DISTRIBUTION_REINVEST,
  isAllEpf: false,
  signatory: PERSONAL_DETAILS.OPTION_CONTROL_PRINCIPAL,
  principal: {
    addressInformation: {
      mailingAddress: {
        address: {
          line1: "",
          line2: undefined,
          line3: undefined,
        },
        city: "",
        country: "",
        postCode: "",
        state: "",
      },
      permanentAddress: {
        address: {
          line1: "",
          line2: undefined,
          line3: undefined,
        },
        city: "",
        country: "",
        postCode: "",
        state: "",
      },
      sameAddress: true,
    },
    bankSummary: {
      localBank: [
        {
          bankAccountName: "Edgar Constantine",
          bankAccountNumber: "7283718281",
          bankLocation: DICTIONARY_COUNTRIES[0].value,
          bankName: "CIMB Bank Berhad",
          bankSwiftCode: "",
          currency: [DICTIONARY_CURRENCY[0].value],
          otherBankName: "",
        },
      ],
      foreignBank: [
        {
          bankAccountName: "Edgar Constantine",
          bankAccountNumber: "8393107410",
          bankLocation: "Switzerland",
          bankName: "Swiss National Bank",
          bankSwiftCode: "SB39110",
          currency: [DICTIONARY_CURRENCY[0].value, DICTIONARY_CURRENCY[1].value],
          otherBankName: "",
        },
      ],
    },
    contactDetails: {
      emailAddress: "",
      contactNumber: [
        {
          code: DICTIONARY_MOBILE_CODE[0].value,
          id: DICTIONARY_MOBILE_CODE[0].id,
          label: PERSONAL_DETAILS.LABEL_MOBILE_NUMBER,
          value: "",
        },
      ],
    },
    declaration: {
      crs: {
        acceptCrs: false,
        taxResident: -1,
        tin: [
          {
            country: "",
            explanation: "",
            explanationSaved: true,
            noTin: false,
            reason: -1,
            tinNumber: "",
          },
        ],
      },
      fatca: {
        acceptFatca: false,
        formW9: false,
        formW8Ben: false,
        confirmAddress: -1,
        certificate: undefined,
        explanation: "",
        explanationSaved: true,
        noCertificate: false,
        reason: -1,
        uploadLater: false,
        usBorn: -1,
        usCitizen: -1,
      },
      fea: {
        acceptFea: false,
        balance: "",
        facility: -1,
        resident: -1,
      },
    },
    epfDetails: {
      epfAccountType: "",
      epfMemberNumber: "",
    },
    employmentDetails: {
      businessNature: "",
      employerName: "",
      occupation: "",
      address: {
        line1: "",
        line2: undefined,
        line3: undefined,
      },
      city: "",
      country: DICTIONARY_COUNTRIES[0].value,
      postCode: "",
      state: "",
    },
    personalDetails: {
      bumiputera: PERSONAL_DETAILS.OPTION_BUMIPUTERA_NO,
      countryOfBirth: "",
      dateOfBirth: undefined,
      educationLevel: "",
      enableBankDetails: false,
      expirationDate: undefined,
      gender: "",
      id: {
        frontPage: undefined,
        secondPage: undefined,
      },
      idNumber: "",
      idType: "",
      maritalStatus: "",
      mothersMaidenName: "",
      monthlyHouseholdIncome: "",
      name: "",
      nationality: "",
      otherEducationLevel: "",
      otherRelationship: "",
      placeOfBirth: "",
      race: "",
      relationship: "",
      riskProfile: "",
      salutation: "",
    },
  },
  joint: {
    addressInformation: {
      mailingAddress: {
        address: {
          line1: "",
          line2: undefined,
          line3: undefined,
        },
        city: "",
        country: "",
        postCode: "",
        state: "",
      },
      permanentAddress: {
        address: {
          line1: "",
          line2: undefined,
          line3: undefined,
        },
        city: "",
        country: "",
        postCode: "",
        state: "",
      },
      sameAddress: true,
    },
    bankSummary: {
      localBank: [
        {
          bankAccountName: "",
          bankAccountNumber: "",
          bankLocation: "",
          bankName: "",
          bankSwiftCode: "",
          currency: [DICTIONARY_CURRENCY[0].value],
          otherBankName: "",
        },
      ],
      foreignBank: [],
    },
    contactDetails: {
      emailAddress: "",
      contactNumber: [
        {
          code: DICTIONARY_MOBILE_CODE[0].value,
          id: DICTIONARY_MOBILE_CODE[0].id,
          label: PERSONAL_DETAILS.LABEL_MOBILE_NUMBER,
          value: "",
        },
      ],
    },
    declaration: {
      crs: {
        acceptCrs: false,
        taxResident: -1,
        tin: [
          {
            country: "",
            explanation: "",
            explanationSaved: true,
            noTin: false,
            reason: -1,
            tinNumber: "",
          },
        ],
      },
      fatca: {
        acceptFatca: false,
        formW9: false,
        formW8Ben: false,
        certificate: undefined,
        confirmAddress: -1,
        explanation: "",
        explanationSaved: true,
        noCertificate: false,
        reason: -1,
        uploadLater: false,
        usBorn: -1,
        usCitizen: -1,
      },
      fea: {
        acceptFea: false,
        balance: "",
        facility: -1,
        resident: -1,
      },
    },
    epfDetails: {
      epfAccountType: "",
      epfMemberNumber: "",
    },
    employmentDetails: {
      businessNature: "",
      employerName: "",
      isEnabled: true,
      grossIncome: "",
      occupation: "",
      address: {
        line1: "",
        line2: undefined,
        line3: undefined,
      },
      city: "",
      country: DICTIONARY_COUNTRIES[0].value,
      postCode: "",
      state: "",
    },
    personalDetails: {
      bumiputera: PERSONAL_DETAILS.OPTION_BUMIPUTERA_NO,
      countryOfBirth: "",
      dateOfBirth: undefined,
      educationLevel: "",
      expirationDate: undefined,
      gender: "",
      id: {
        frontPage: undefined,
        secondPage: undefined,
      },
      idNumber: "",
      idType: "",
      maritalStatus: "",
      mothersMaidenName: "",
      monthlyHouseholdIncome: "",
      name: "",
      nationality: "",
      otherEducationLevel: "",
      otherRelationship: "",
      placeOfBirth: "",
      race: "",
      riskProfile: "",
      salutation: "",
    },
  },
};
