export const NEW_SALES_ROUTES: INewSalesRoutes = {
  AccountList: "AccountList",
  AccountInformation: "AccountInformation",
  Acknowledgement: "Acknowledgement",
  AdditionalDetails: "AdditionalDetails",
  IdentityVerification: "IdentityVerification",
  OrderPreview: "OrderPreview",
  Payment: "Payment",
  Products: "Products",
  ProductsConfirmation: "ProductsConfirmation",
  ProductsList: "ProductsList",
  RiskAssessment: "RiskAssessment",
  RiskSummary: "RiskSummary",
  Signatures: "Signatures",
  Summary: "Summary",
  TermsAndConditions: "TermsAndConditions",
};

export const NEW_SALES_KEYS: INewSalesKeys = {
  AccountList: "AccountList",
  AccountInformation: "AccountInformation",
  Acknowledgement: "Acknowledgement",
  AdditionalDetails: "AdditionalDetails",
  IdentityVerification: "IdentityVerification",
  OrderPreview: "OrderPreview",
  Products: "Products",
  Payment: "Payment",
  ProductsConfirmation: "ProductsConfirmation",
  ProductsList: "ProductsList",
  RiskAssessment: "RiskAssessment",
  RiskSummary: "RiskSummary",
  Signatures: "Signatures",
  Summary: "Summary",
  TermsAndConditions: "TermsAndConditions",
};
