export const NEW_SALES_ROUTES: INewSalesRoutes = {
  AccountList: "AccountList",
  Acknowledgement: "Acknowledgement",
  AdditionalDetails: "AdditionalDetails",
  IdentityVerification: "IdentityVerification",
  OrderPreview: "OrderPreview",
  Payment: "Payment",
  ProductsConfirmation: "ProductsConfirmation",
  ProductsList: "ProductsList",
  RiskAssessment: "RiskAssessment",
  RiskProfile: "RiskProfile",
  Signatures: "Signatures",
  Summary: "Summary",
  TermsAndConditions: "TermsAndConditions",
};

export const NEW_SALES_KEYS: INewSalesKeys = {
  AccountList: "AccountList",
  Acknowledgement: "Acknowledgement",
  AdditionalDetails: "AdditionalDetails",
  IdentityVerification: "IdentityVerification",
  OrderPreview: "OrderPreview",
  Payment: "Payment",
  ProductsConfirmation: "ProductsConfirmation",
  ProductsList: "ProductsList",
  RiskAssessment: "RiskAssessment",
  RiskProfile: "RiskProfile",
  Signatures: "Signatures",
  Summary: "Summary",
  TermsAndConditions: "TermsAndConditions",
};
