export const ONBOARDING_ROUTES: IOnboardingRoutes = {
  Acknowledgement: "Acknowledgement",
  AdditionalDetails: "AdditionalDetails",
  ContactDetails: "ContactDetails",
  CRSDeclaration: "CRSDeclaration",
  Declarations: "Declarations",
  DeclarationSummary: "DeclarationSummary",
  EmailVerification: "EmailVerification",
  EmploymentDetails: "EmploymentDetails",
  FATCADeclaration: "FATCADeclaration",
  IdentityVerification: "IdentityVerification",
  OrderSummary: "OrderSummary",
  Payment: "Payment",
  PersonalInformation: "PersonalInformation",
  PersonalInfoSummary: "PersonalInfoSummary",
  Products: "Products",
  RiskAssessment: "RiskAssessment",
  RiskSummary: "RiskSummary",
  Signatures: "Signatures",
  TermsAndConditions: "TermsAndConditions",
};

export const ONBOARDING_KEYS: IOnboardingKeys = {
  RiskAssessment: "RiskAssessment",
  RiskSummary: "RiskSummary",
  Products: "Products",
  PersonalInformation: "PersonalInformation",
  EmailVerification: "EmailVerification",
  IdentityVerification: "IdentityVerification",
  ContactDetails: "ContactDetails",
  EmploymentDetails: "EmploymentDetails",
  AdditionalDetails: "AdditionalDetails",
  PersonalInfoSummary: "PersonalInfoSummary",
  Declarations: "Declarations",
  FATCADeclaration: "FATCADeclaration",
  CRSDeclaration: "CRSDeclaration",
  DeclarationSummary: "DeclarationSummary",
  Acknowledgement: "Acknowledgement",
  OrderSummary: "OrderSummary",
  TermsAndConditions: "TermsAndConditions",
  Signatures: "Signatures",
  Payment: "Payment",
};
