export const ONBOARDING_ROUTES: IOnboardingRoutes = {
  CRSDeclaration: "CRSDeclaration",
  DeclarationSummary: "DeclarationSummary",
  EmailVerification: "EmailVerification",
  EmploymentDetails: "EmploymentDetails",
  FATCADeclaration: "FATCADeclaration",
  FEADeclarations: "FEADeclaration",
  IdentityVerification: "IdentityVerification",
  OrderSummary: "OrderSummary",
  Payment: "Payment",
  PersonalDetails: "PersonalDetails",
  PersonalInfoSummary: "PersonalInfoSummary",
  ProductRecommendation: "ProductRecommendation",
  RiskAssessment: "RiskAssessment",
  TermsAndConditions: "TermsAndConditions",
};
