export const ONBOARDING_ROUTES: IOnboardingRoutes = {
  CRSDeclaration: "CRSDeclaration",
  DeclarationSummary: "DeclarationSummary",
  EmailVerification: "EmailVerification",
  EmploymentDetails: "EmploymentDetails",
  FATCADeclaration: "FATCADeclaration",
  FEADeclarations: "FEADeclaration",
  IdentityVerification: "IdentityVerification",
  OrderSummary: "OrderSummary",
  Payment: "Payment",
  PersonalDetails: "PersonalDetails",
  PersonalInfoSummary: "PersonalInfoSummary",
  ProductRecommendation: "ProductRecommendation",
  RiskAssessment: "RiskAssessment",
  Signatures: "Signatures",
  TermsAndConditions: "TermsAndConditions",
};

export const ONBOARDING_KEYS: IOnboardingKeys = {
  RiskAssessment: "RiskAssessment",
  Products: "Products",
  PersonalInformation: "PersonalInformation",
  EmailVerification: "EmailVerification",
  IdentityVerification: "IdentityVerification",
  PersonalDetails: "PersonalDetails",
  EmploymentDetails: "EmploymentDetails",
  PersonalInfoSummary: "PersonalInfoSummary",
  Declarations: "Declarations",
  FATCADeclaration: "FATCADeclaration",
  FEADeclaration: "FEADeclaration",
  CRSDeclaration: "CRSDeclaration",
  DeclarationSummary: "DeclarationSummary",
  Acknowledgement: "Acknowledgement",
  OrderSummary: "OrderSummary",
  TermsAndConditions: "TermsAndConditions",
  Signatures: "Signatures",
  Payment: "Payment",
};
